<!DOCTYPE html>
<html>
    <head>
        <title>Dashboard Report</title>
    </head>
    <body>

        <style>
            .custom_row{
                display: table;
                width: 100%;
                /* margin-top: 20px; */
            }
            .custom_col{
                display: table-cell;
                width: 33%;
                padding: 10px;
            }

            .custom_tbl_css{
                table-layout: auto;
                width: 100%;
                border-radius: 0px 0px 10px 10px;
                border: 2px solid #446161;
                border-collapse: separate;
                /* border-bottom: 1px solid #446161; */
            }
            th, td {
                padding: 8px;
                text-align: center;
                border-right: 1px solid #ddd;
                border-bottom: 1px solid #ddd;
            }

            /* Remove border-right from the last column in each row */
            .custom_tbl_css td:last-child, .custom_tbl_css th:last-child {
                border-right: none;
            }
            /* Remove border-bottom from the last row */
            .custom_tbl_css tr:last-child td,
            .custom_tbl_css tr:last-child th
            {
                border-bottom: none;
            }

            .custom_tbl_caption_css{
                caption-side: top;
                font-weight: 700;
                color: white;
                background: #446161;
                border-radius: 10px 10px 0px 0px;
                padding: 5px;
            }

            .custom_tr_th th
            {
                border-bottom: 1px solid #ddd !important;
            }
            .custom_tr_td tr:last-child td{
                border-bottom: 1px solid #ddd !important;
            }
            .custom_span{
                color: #446161;
                font-weight: bold;
                border: 1px solid #446161;
                border-radius: 5px;
                padding:3px;
                margin-top:10px;
                margin-bottom:1px;
                display: inline-block;
                white-space: normal;
            }
            .custom_input_div{
                border: 1px solid #446161;
                padding:10px;
                border-radius: 5px;
                margin-top: 2px;
            }
        </style>

        <div class="body_container">

            <h1>Dashboard Report</h1>
            <p>This PDF document is generated by  <b style="color: red">{{ Auth::user()->name }} </b> on  {{ \Carbon\Carbon::now('Asia/Karachi')->format('l, d-M-Y h:i A') }}.</p>

            <div class="custom_row">

                <div class="custom_col">
                    <label>Selected Time Period </label>
                    @php
                        if(app('request')->input('time_period') == 'today'){
                            $selected_time_period = 'Today';
                        }elseif(app('request')->input('time_period') == 'this_week'){
                            $selected_time_period = 'This Week';
                        }elseif(app('request')->input('time_period') == 'last_week'){
                            $selected_time_period = 'Last Week';
                        }elseif(app('request')->input('time_period') == 'this_month'){
                            $selected_time_period = 'This Month';
                        }elseif(app('request')->input('time_period') == 'last_month'){
                            $selected_time_period = 'Last Month';
                        }elseif(app('request')->input('time_period') == 'three_month'){
                            $selected_time_period = 'Three Month';
                        }elseif(app('request')->input('time_period') == 'six_month'){
                            $selected_time_period = 'Six Month';
                        }elseif(app('request')->input('time_period') == 'this_year'){
                            $selected_time_period = 'This Year';
                        }else{
                            $selected_time_period = 'Custom Date';
                        }
                    @endphp

                    <div class="custom_input_div">
                        {{ $selected_time_period}}
                    </div>

                </div>

                @if (app('request')->input('time_period') == 'custom_date')
                    <div class="custom_col">
                        <label> Start Date </label>
                        {{-- <input type="text"  readonly value="{{app('request')->input('startDate')}}"> --}}
                        <div class="custom_input_div">
                            {{app('request')->input('startDate')}}
                        </div>
                    </div>
                    <div class="custom_col">
                        <label> End Date </label>
                        {{-- <input type="text" readonly value="{{app('request')->input('endDate')}}"> --}}
                        <div class="custom_input_div">
                            {{app('request')->input('endDate')}}
                        </div>
                    </div>
                @endif

            </div>

            <div class="custom_row" >
                <div class="custom_col">
                    <label>Selected User </label>
                    @php
                        // Fetch selected user IDs from request or default to current user ID
                        $selectedUserIds = app('request')->input('users', [Auth::user()->id]);
                        // Check if 'all_active_user' is in the selected user IDs
                        if (in_array('all_active_user', $selectedUserIds)) {
                            $selectedUserIds = ['all_active_user']; // Set it to an array with just 'all_active_user'
                            $selectedUsersString = "All";
                        }else {
                            $selectedUserNames = $graph_users->whereIn('id', $selectedUserIds)->pluck('name')->toArray();
                            $selectedUsersString = implode(' ', array_map(function($name)
                            {
                                return "<span class = 'custom_span'>$name</span>";
                            }, $selectedUserNames));
                        }
                    @endphp

                    <div class="custom_input_div">
                        {!! $selectedUsersString !!}
                    </div>

                </div>
            </div>


            <?php

                if ($user_target['set_sales_target' ] > 0){
                    $achive_sales_target = number_format(($user_target['achive_sales_target' ] * 100)/$user_target['set_sales_target' ] , 2) .' %';
                }else {
                    $achive_sales_target =  number_format($user_target['set_sales_target' ] , 2) .' %';
                }

                if ($user_target['set_unit_target' ] > 0){
                    $achive_unit_target = number_format(($user_target['achive_unit_target' ] * 100)/$user_target['set_unit_target' ] , 2) .' %';
                }else {
                    $achive_unit_target = number_format($user_target['set_unit_target' ] , 2) .' %';
                }


                if ($user_target['set_verified_calls_target' ] > 0){
                    $achive_verified_calls_target = number_format(($user_target['achive_verified_calls_target' ] * 100)/$user_target['set_verified_calls_target' ] , 2) .' %';
                }else {
                    $achive_verified_calls_target = number_format($user_target['set_verified_calls_target' ] , 2) .' %';
                }


                if ($user_target['set_client_meetings_target' ] > 0){
                    $achive_client_meetings_target = number_format(($user_target['achive_client_meetings_target' ] * 100)/$user_target['set_client_meetings_target' ] , 2) .' %';
                }else {
                    $achive_client_meetings_target = number_format($user_target['set_client_meetings_target' ] , 2) .' %';
                }

                if ($user_target['set_site_visit_target' ] > 0){
                    $achive_site_visit_target = number_format(($user_target['achive_site_visit_target' ] * 100)/$user_target['set_site_visit_target' ] , 2) .' %';
                }else {
                    $achive_site_visit_target = number_format($user_target['set_site_visit_target' ] , 2) .' %';
                }

                if ($user_target['set_leads_target' ] > 0){
                    $achive_new_leads_target = number_format(($user_target['achive_new_leads_target' ] * 100)/$user_target['set_leads_target' ] , 2) .' %';
                }else {
                    $achive_new_leads_target = number_format($user_target['set_leads_target' ] , 2) .' %';
                }

                if ($user_target['set_affiliator_target' ] > 0){
                    $achive_affiliator_target = number_format(($user_target['achive_affiliator_target' ] * 100)/$user_target['set_affiliator_target' ] , 2) .' %';
                }else {
                    $achive_affiliator_target = number_format($user_target['set_affiliator_target' ] , 2) .' %';
                }

                if ($user_target['set_dealer_meetings_target' ] > 0){
                    $achive_dealer_meetings_target = number_format(($user_target['achive_dealer_meetings_target' ] * 100)/$user_target['set_dealer_meetings_target' ] , 2) .' %';
                }else {
                    $achive_dealer_meetings_target = number_format($user_target['set_dealer_meetings_target' ] , 2) .' %';
                }

                if ($user_target['set_freelancer_meetings_target' ] > 0){
                    $achive_freelancer_meetings_target = number_format(($user_target['achive_freelancer_meetings_target' ] * 100)/$user_target['set_freelancer_meetings_target' ] , 2) .' %';
                }else {
                    $achive_freelancer_meetings_target = number_format($user_target['set_freelancer_meetings_target' ] , 2) .' %';
                }

            ?>

            <div class="custom_row">
                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Total Units</caption>
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td>{{ number_format($user_target['set_unit_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Achieve</th>
                                <td>{{ number_format($user_target['achive_unit_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Percent</th>
                                <td>{{ $achive_unit_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Total Sales</caption>
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td>{{ number_format($user_target['set_sales_target']). ' Rs' }}</td>

                            </tr>
                            <tr>
                                <th>Achieve</th>
                                <td>{{ number_format($user_target['achive_sales_target']). ' Rs' }}</td>
                            </tr>
                            <tr>
                                <th>Percent</th>
                                <td>{{ $achive_sales_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Tokens</caption>
                        <thead>
                            <tr class="custom_tr_th">
                                <th>Token</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="custom_tr_td">
                                <td>{{ number_format($user_target['achive_number_of_token_target']) }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="custom_row">
                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Contacted / Verified Calls</caption>
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td>{{ number_format($user_target['set_verified_calls_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Achieve</th>
                                <td>{{ number_format($user_target['achive_verified_calls_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Percent</th>
                                <td>{{ $achive_verified_calls_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Client Meetings</caption>
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td>{{ number_format($user_target['set_client_meetings_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Achieve</th>
                                <td>{{ number_format($user_target['achive_client_meetings_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Percent</th>
                                <td>{{ $achive_client_meetings_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Site Vists</caption>
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td>{{ number_format($user_target['set_site_visit_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Achieve</th>
                                <td>{{ number_format($user_target['achive_site_visit_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Percent</th>
                                <td>{{ $achive_site_visit_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="custom_row">

                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">New Leads</caption>
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td>{{ number_format($user_target['set_leads_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Achieve</th>
                                <td>{{ number_format($user_target['achive_new_leads_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Percent</th>
                                <td>{{ $achive_new_leads_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Dealer Meetings</caption>
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td>{{ number_format($user_target['set_dealer_meetings_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Achieve</th>
                                <td>{{ number_format($user_target['achive_dealer_meetings_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Percent</th>
                                <td>{{ $achive_dealer_meetings_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Freelancer Meetings</caption>
                        <tbody>
                            <tr>
                                <th>Total</th>
                                <td>{{ number_format($user_target['set_freelancer_meetings_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Achieve</th>
                                <td>{{ number_format($user_target['achive_freelancer_meetings_target']) }}</td>
                            </tr>
                            <tr>
                                <th>Percent</th>
                                <td>{{ $achive_freelancer_meetings_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="custom_row">

                <div class="custom_col">
                    <table class="custom_tbl_css">
                        <caption class="custom_tbl_caption_css">Total Affiliators</caption>
                        <thead>
                            <tr class="custom_tr_th">
                                <th>Total</th>
                                <th>Achieve</th>
                                <th>Dealer</th>
                                <th>Freelancer</th>
                                <th>Percent</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="custom_tr_td">
                                <td>{{ number_format($user_target['set_affiliator_target']) }}</td>
                                <td>{{ number_format($user_target['achive_affiliator_target']) }}</td>
                                <td>{{ number_format($user_target['dealer']) }}</td>
                                <td>{{ number_format($user_target['freelancer']) }}</td>
                                <td>{{ $achive_affiliator_target }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </body>
</html>
