<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Leads;
use App\Models\Clients;
use App\Models\Offices;
use App\Models\Project;
use App\Models\Compain;
use App\Models\Facebook;
use App\Models\User;
use App\Http\Helpers\Helper;
use App\Models\Category;
use App\Models\Number;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Mail;
use App\Services\FacebookLeadSyncService;


class FacebookApiController extends Controller
{

    public function access_token()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        // new genrate on 06-Apr-2026
        curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v20.0/oauth/access_token?grant_type=fb_exchange_token&client_id=428172866188645&client_secret=e65ea40616e87a9ab6e01fa602e308a5&fb_exchange_token=EAAGFa8OXdWUBRmMEmvZCQVvGeFFw2HeRW2IIDQs3O0HM2zr75Czjd9VZAF6UyTEIIEqPKAHAqPBe6tSjzOZCRSHMZBWH19ZBQMZBHR16v7I63GNAPTsuceyBzq2EASDI1VUQd3GhdM3dCpTFAv0piglJJ6WA8Ty7rLKJYF29CSFZA7HSX7JEdOifBVE1Wyc05fEd77jLWyCpxe7xZA0zbhiTFhdfu4tfsPbLvUhGuYty4Y4OrY5Y');

        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $result = curl_exec($ch);
        $record = json_decode($result);

        //echo '<pre>';
        //print_r(json_decode($result));
        // exit;

        $date = date('Y-m-d H:i:s', (time() + $record->expires_in));
        // exit;
        $data = array(
            'client_id' => '428172866188645',
            'client_secret' => 'e65ea40616e87a9ab6e01fa602e308a5',
            'page_id' => '104042691883897',
            'long_lived_token' => $record->access_token,
            'token_type' => $record->token_type,
            'expires_at' => $date
        );

        $recoed_created = Facebook::create($data);

        $get_first_recoed = Facebook::first();
        Facebook::where('id', $get_first_recoed->id)->update(['id' => $recoed_created['id'] + 1]);
        Facebook::where('id', $recoed_created['id'])->update(['id' => 1]);

        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        echo "done";
    }

    // public function facebookleads()
    // {
    //     if (!Auth::user()->can('facebook.leads.sync')) {
    //         return redirect('/')->withErrors(__('Doesn\'t have permission to access this resource'));
    //     }

    //     set_time_limit(600); // 10 minutes
    //     ini_set('max_execution_time', 600);

    //     $counter = 0;
    //     $facebook = Facebook::find(1);
    //     $campaigns = Compain::where('status', 1)->get();
    //     $data = [
    //         'name' => 'Facebook',
    //         'counter' => 0
    //     ];

    //     $ch = curl_init();
    //     curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    //     curl_setopt($ch, CURLOPT_TIMEOUT, 60);

    //     foreach ($campaigns as $campaign) {

    //         if (empty($campaign->form_id)) {
    //             continue;
    //         }

    //         // ============================================
    //         // CHANGE #1: Track if sync completed successfully
    //         // ============================================
    //         $syncSuccess = true;

    //         // ============================================
    //         // CHANGE #2: Build API parameters
    //         // ============================================
    //         $params = [
    //             'access_token' => $facebook->long_lived_token,
    //             'fields' => 'id,form_id,field_data'
    //         ];

    //         // ============================================
    //         // CHANGE #3: Fetch only leads after last sync
    //         // ============================================
    //         if (!empty($campaign->last_synced_at)) {
    //             $params['since'] = strtotime($campaign->last_synced_at);
    //         }

    //         $url = 'https://graph.facebook.com/v20.0/' .
    //             $campaign->form_id .
    //             '/leads?' .
    //             http_build_query($params);

    //         do {

    //             curl_setopt($ch, CURLOPT_URL, $url);
    //             $result = curl_exec($ch);

    //             if (curl_errno($ch)) {

    //                 Log::error('Facebook CURL Error', [
    //                     'campaign_id' => $campaign->id,
    //                     'error' => curl_error($ch)
    //                 ]);

    //                 $syncSuccess = false;
    //                 break;
    //             }

    //             $records = json_decode($result);

    //             // ============================================
    //             // CHANGE #4: Handle Facebook API errors
    //             // ============================================
    //             if (isset($records->error)) {

    //                 Log::error('Facebook API Error', [
    //                     'campaign_id' => $campaign->id,
    //                     'form_id' => $campaign->form_id,
    //                     'error' => $records->error,
    //                     'url' => $url
    //                 ]);

    //                 $syncSuccess = false;
    //                 break;
    //             }

    //             if (!empty($records->data) && is_array($records->data)) {

    //                 foreach ($records->data as $record) {

    //                     if (!empty($record->form_id)) {

    //                         //  STEP 1: Prevent duplicate Facebook lead
    //                         if (Leads::where('facebook_lead_id', $record->id)->exists()) {
    //                             continue;
    //                         }

    //                         $lead_id = $this->leadsync($record, $campaign, $facebook->long_lived_token);

    //                         if ($lead_id > 0) {
    //                             $counter++;
    //                         }
    //                     }
    //                 }
    //             }

    //             // Facebook Pagination
    //             $url = $records->paging->next ?? null;
    //         } while ($url);

    //         // ============================================
    //         // CHANGE #5: Update last_synced_at
    //         // ONLY when sync completed successfully
    //         // ============================================
    //         if ($syncSuccess) {

    //             $campaign->update([
    //                 'last_synced_at' => now()
    //             ]);

    //             Log::info('Facebook campaign synced', [
    //                 'campaign_id' => $campaign->id,
    //                 'last_synced_at' => now()
    //             ]);
    //         }
    //     }

    //     curl_close($ch);

    //     if ($counter > 0) {

    //         // Auth User Notification
    //         Helper::notification([
    //             'type' => 'Added New Lead',
    //             'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
    //             'created_by' => Auth::user()->id,
    //             'show_to' => Auth::user()->id,
    //             'show_to_role' => 0,
    //             'redirect' => 'newleads',
    //         ]);

    //         // Parent User Notification
    //         Helper::notification([
    //             'type' => 'Added New Lead',
    //             'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
    //             'created_by' => Auth::user()->id,
    //             'show_to' => Auth::user()->parent,
    //             'show_to_role' => 0,
    //             'redirect' => 'newleads',
    //         ]);

    //         // Role Users Notification
    //         $roleUsers = User::whereIn('role', [13, 14])->get();

    //         foreach ($roleUsers as $roleUser) {

    //             if (
    //                 Auth::user()->parent != $roleUser->id &&
    //                 Auth::user()->role != $roleUser->role
    //             ) {

    //                 Helper::notification([
    //                     'type' => 'Added New Lead',
    //                     'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
    //                     'created_by' => Auth::user()->id,
    //                     'show_to' => $roleUser->id,
    //                     'show_to_role' => 0,
    //                     'redirect' => 'newleads',
    //                 ]);
    //             }
    //         }

    //         $data = [
    //             'name' => 'Facebook',
    //             'counter' => $counter
    //         ];
    //     }

    //     Mail::send('mail', $data, function ($message) {
    //         $message->to([
    //             'shahid.shahid34@gmail.com' => 'Shahid Iqbal',
    //             'hassanraza74659@gmail.com' => 'Hassan Raza'
    //         ])->subject('Fairy Marketing Facebook Lead Notification');
    //         $message->from(config('mail.from.address'), config('mail.from.name'));
    //     });

    //     return redirect('newleads')
    //         ->withStatus(__('FaceBook Leads Sync Successfully. Total Leads: ' . $counter));
    // }

    // public function leadsync($result, $campaign, $facebook_long_lived_token = null)
    // {
    //     $name = '';
    //     $email = '';
    //     $phone = '';
    //     $address = '';
    //     $lead_id = 0;
    //     $category_id = null;
    //     $check_phone = null;

    //     // Skip if field_data missing
    //     if (
    //         empty($result->field_data) ||
    //         !is_array($result->field_data)
    //     ) {
    //         return 0;
    //     }

    //     foreach ($result->field_data as $field) {

    //         $value = isset($field->values) && isset($field->values[0])
    //             ? trim($field->values[0])
    //             : '';

    //         // echo '<pre>';
    //         // print_r($result->field_data);
    //         // echo '<br>';echo '======================';echo '<br>';
    //         // exit;

    //         if ($field->name == 'are_you_interested_in_shop_or_appartments') {
    //             $category_name = $value;
    //             $category_slug = strtolower(str_replace(' ', '-', $category_name));

    //             $category = Category::where('name', $category_name)->orWhere('slug', $category_name)->first();
    //             if ($category) {
    //                 $category_id = $category->id;
    //             } else {
    //                 $category = Category::Create([
    //                     'name' => $category_name,
    //                     'slug' => $category_slug,
    //                     'description' => $category_name,
    //                 ]);
    //                 $category_id = $category->id;
    //             }
    //         } elseif ($field->name == 'full_name' || $field->name == 'your_name'  || $field->name == 'full name') {
    //             $name = $value;
    //         } elseif ($field->name == 'email') {
    //             $email = $value;
    //         } elseif ($field->name == 'phone_number') {
    //             $phone = $value;
    //             $check_0 = mb_substr($phone, 0, 1);         // Get the first characters for 0 check
    //             $check_plus_92 = mb_substr($phone, 0, 3);   // Get the first three characters for +92 check
    //             if ($check_0 == '0') {
    //                 $check_phone = mb_substr($phone, 1);    // Remove the first 0 character
    //             } elseif ($check_plus_92 == '+92') {
    //                 $check_phone = mb_substr($phone, 3);    // Remove the first three +92 characters
    //             } else {
    //                 $check_phone = $value;
    //             }
    //         } elseif ($field->name == 'city') {
    //             $address = $value;
    //         }
    //     }

    //     // echo 'name = ';
    //     // print_r($name);
    //     // echo '<br>';
    //     // echo 'email = ';
    //     // print_r($email);
    //     // echo '<br>';
    //     // echo 'phone_number = ';
    //     // print_r($check_phone);
    //     // echo '<br>';
    //     // echo 'city = ';
    //     // print_r($address);
    //     // echo '<br>';
    //     // echo 'Category ID updated= ';
    //     // print_r($category_id);
    //     // echo '<br>';
    //     // echo '==========================================';
    //     // echo '<br>';
    //     // exit;

    //     // $client = Clients::where('phone', $check_phone)->orWhere('email', $email)->first();
    //     // $client_record = Number::Where('number', 'like', '%' . $check_phone . '%')->Where('type', 'clients')->first();

    //     $client = null;
    //     $client_record = null;

    //     // if (!empty($check_phone)) { $client = Clients::where('phone', $check_phone)->first();}
    //     // elseif (!empty($email)) {$client = Clients::where('email', $email)->first(); }

    //     $client = Clients::where('phone', $check_phone)
    //         ->when(!empty($email), function ($query) use ($email) {
    //             $query->orWhere('email', $email);
    //         })
    //         ->first();

    //     if (!empty($check_phone)) {
    //         $client_record = Number::where('number', $check_phone)->where('type', 'clients')->first();
    //     }

    //     if (empty($client) && empty($client_record) && !empty($campaign)) {

    //         $attributes = ['phone' => $phone];
    //         if (!empty($email)) {
    //             $attributes['email'] = $email;
    //         }

    //         $client = Clients::firstOrCreate(
    //             $attributes,
    //             [
    //                 'name' => $name,
    //                 'email' => $email,
    //                 'phone' => $phone,
    //                 'address' => $address,
    //                 'source_id' => 3,
    //                 'office_id' => $campaign->office_id,
    //             ]
    //         );

    //         $lead = Leads::create([
    //             'client_id' => $client->id,
    //             'project_id' => $campaign->project_id,
    //             'source_id' => 3,
    //             'office_id' => $campaign->office_id,
    //             'category_id' => $category_id,
    //             'facebook_lead_id' => $result->id,

    //         ]);
    //         $lead_id = $lead->id;

    //         Number::insert(['number' => $phone, 'type' => 'clients', 'client_id' => $client->id,]);

    //         app(\App\Services\MetaCapiService::class)->sendLeadEvent($client, $lead, $campaign, $facebook_long_lived_token, $context = 'web');
    //     } else {
    //         if (!empty($client) && !empty($client_record) && !empty($campaign)) {
    //             $leads = Leads::where('client_id', $client['id'])->where('project_id', $campaign->project_id)->get();

    //             if ($leads->isEmpty()) {
    //                 $lead = Leads::create([
    //                     'client_id' => $client['id'],
    //                     'project_id' => $campaign->project_id,
    //                     'source_id' => 3,
    //                     'user_id' => $client['user_id'],
    //                     'office_id' => $campaign->office_id,
    //                     'category_id' => $category_id,
    //                     'facebook_lead_id' => $result->id,

    //                 ]);
    //                 $lead_id = $lead->id;

    //                 app(\App\Services\MetaCapiService::class)->sendLeadEvent($client, $lead, $campaign, $facebook_long_lived_token, $context = 'web');
    //             }
    //         }
    //     }

    //     return $lead_id; // Return lead_id if set, otherwise null

    // }

    public function facebookleads(FacebookLeadSyncService $syncService)
    {
        if (!Auth::user()->can('facebook.leads.sync')) {
            return redirect('/')->withErrors(__('Doesn\'t have permission to access this resource'));
        }

        set_time_limit(300); // 5 minutes
        ini_set('max_execution_time', 300);

        $counter = $syncService->sync('web');

        if ($counter > 0) {

            // Auth User Notification
            Helper::notification([
                'type' => 'Added New Lead',
                'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
                'created_by' => Auth::user()->id,
                'show_to' => Auth::user()->id,
                'show_to_role' => 0,
                'redirect' => 'newleads',
            ]);

            // Parent User Notification
            Helper::notification([
                'type' => 'Added New Lead',
                'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
                'created_by' => Auth::user()->id,
                'show_to' => Auth::user()->parent,
                'show_to_role' => 0,
                'redirect' => 'newleads',
            ]);

            // Role Users Notification
            $roleUsers = User::whereIn('role', [13, 14])->get();

            foreach ($roleUsers as $roleUser) {

                if (
                    Auth::user()->parent != $roleUser->id &&
                    Auth::user()->role != $roleUser->role
                ) {

                    Helper::notification([
                        'type' => 'Added New Lead',
                        'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
                        'created_by' => Auth::user()->id,
                        'show_to' => $roleUser->id,
                        'show_to_role' => 0,
                        'redirect' => 'newleads',
                    ]);
                }
            }

            $mailData = [
                'name' => 'Facebook',
                'counter' => $counter
            ];

            Mail::send('mail', $mailData, function ($message) {
                $message->to([
                    'shahid.shahid34@gmail.com' => 'Shahid Iqbal',
                    'hassanraza74659@gmail.com' => 'Hassan Raza'
                ])->subject('Fairy Marketing Facebook Lead Notification');
                $message->from(config('mail.from.address'), config('mail.from.name'));
            });
        }

        return redirect('newleads')->withStatus(__('FaceBook Leads Sync Successfully. Total Leads: ' . $counter));
    }
}
