<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Leads;
use App\Models\Clients;
use App\Models\Offices;
use App\Models\Project;
use App\Models\Compain;
use App\Models\Facebook;
use App\Models\User;
use App\Http\Helpers\Helper;
use App\Models\Category;
use App\Models\Number;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Mail;
use App\Services\FacebookLeadSyncService;


class FacebookApiController extends Controller
{

    public function access_token()
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        // new genrate on 08-Aug-2026
        curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v20.0/oauth/access_token?grant_type=fb_exchange_token&client_id=428172866188645&client_secret=e65ea40616e87a9ab6e01fa602e308a5&fb_exchange_token=EAAGFa8OXdWUBSHSyzcDN1hYzXYudm13b9CRjDsWTuKjwW6KMdxBEkIZC0jasWzkdjfV96StMIha8DZCeZAlBJaHiNswkfmTBZBdUX1sVAWUWV33P4jPRPzxZCIh5pYx91JTyXARZCJ3AvLSJdKZCfBCsdFXCTsbT4Wfl7ILcRUPc8dlgYDqGkbwXVN2VRFnTkAJJ3ZBZCrgEIGd66z5QhZBI1tzzKOLoXROYj5iyWZCexMKJ3GUiE7IMAZDZD');

        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $result = curl_exec($ch);
        $record = json_decode($result);

        // echo '<pre>';print_r(json_decode($result)); exit;

        $date = date('Y-m-d H:i:s', (time() + $record->expires_in));

        $data = array(
            'client_id' => '428172866188645',
            'client_secret' => 'e65ea40616e87a9ab6e01fa602e308a5',
            'page_id' => '104042691883897',
            'long_lived_token' => $record->access_token,
            'token_type' => $record->token_type,
            'expires_at' => $date
        );

        $recoed_created = Facebook::create($data);

        $get_first_recoed = Facebook::first();
        Facebook::where('id', $get_first_recoed->id)->update(['id' => $recoed_created['id'] + 1]);
        Facebook::where('id', $recoed_created['id'])->update(['id' => 1]);

        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        echo "done";
    }


    public function facebookleads(FacebookLeadSyncService $syncService)
    {
        if (!Auth::user()->can('facebook.leads.sync')) {
            return redirect('/')->withErrors(__('Doesn\'t have permission to access this resource'));
        }

        set_time_limit(300); // 5 minutes
        ini_set('max_execution_time', 300);

        $counter = $syncService->sync('web');

        if ($counter > 0) {

            // Auth User Notification
            Helper::notification([
                'type' => 'Added New Lead',
                'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
                'created_by' => Auth::user()->id,
                'show_to' => Auth::user()->id,
                'show_to_role' => 0,
                'redirect' => 'newleads',
            ]);

            // Parent User Notification
            Helper::notification([
                'type' => 'Added New Lead',
                'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
                'created_by' => Auth::user()->id,
                'show_to' => Auth::user()->parent,
                'show_to_role' => 0,
                'redirect' => 'newleads',
            ]);

            // Role Users Notification
            $roleUsers = User::whereIn('role', [13, 14])->get();

            foreach ($roleUsers as $roleUser) {

                if (
                    Auth::user()->parent != $roleUser->id &&
                    Auth::user()->role != $roleUser->role
                ) {

                    Helper::notification([
                        'type' => 'Added New Lead',
                        'msg_body' => 'New ' . $counter . ' Leads landed In CRM From FaceBook.',
                        'created_by' => Auth::user()->id,
                        'show_to' => $roleUser->id,
                        'show_to_role' => 0,
                        'redirect' => 'newleads',
                    ]);
                }
            }

            $mailData = [
                'name' => 'Facebook',
                'counter' => $counter
            ];

            Mail::send('mail', $mailData, function ($message) {
                $message->to([
                    'shahid.shahid34@gmail.com' => 'Shahid Iqbal',
                    'hassanraza74659@gmail.com' => 'Hassan Raza'
                ])->subject('Fairy Marketing Facebook Lead Notification');
                $message->from(config('mail.from.address'), config('mail.from.name'));
            });
        }

        return redirect('newleads')->withStatus(__('FaceBook Leads Sync Successfully. Total Leads: ' . $counter));
    }
}
