<!DOCTYPE html>
<html>
<head>
    <title>All Types of Reports</title>
</head>
<body>

    <style>
        table.table.ps-table th{
            background: #446161;
            color: #fff;
            font-weight: 600;
        }
        .ps-table {
            background-color: #fff;
        }
        table {
            border-collapse: separate; /*collapse;*/
            border-spacing: 1px;
        }

        .table > thead > tr > th {
            vertical-align: bottom;
            border-bottom: 2px solid #dddddd;
        }

        .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
            padding: 8px;
        }

        .ps-table tbody tr td {
            font-size: 14px;
            padding: 12px 10px;
            border: none;
            margin: 0 auto;
            vertical-align: middle;
        }
    </style>

    <h1>All Types of Reports</h1>
    <p>This PDF document is generated by  <b style="color: red">{{ Auth::user()->name }} </b> on  {{ \Carbon\Carbon::now('Asia/Karachi')->format('l, d-M-Y h:i A') }}.</p>

    <?php
        // $user_id = 0;
        if(app('request')->input('task') != ''){
            $select_task = app('request')->input('task');
        }else{
            $select_task = 'all';
        }

        $followed_up='Followed Up';
        $contacted_client='Contacted Client';
        $call_attempt='Call Attempt';
        $whatsapp_call='Whatsapp Call';

        $meeting_done ='Meeting (Done)';
        $meeting_arranged ='Meeting (Arranged)';
        $meeting_attempt ='Meeting (Attempt)';
        $meeting_pushed ='Meeting (Pushed)';
    ?>

    <table class="table ps-table" style="width: 100%; table-layout: fixed;">
        <thead>
            <tr>
                <th style="width:15%;">User</th>
                <th style="text-align:center;">Followed Up</th>
                <th style="text-align:center;">Contacted Client</th>
                <th style="text-align:center;">Call Attempt</th>
                <th style="text-align:center;"> WhatsApp Call </th>

                <th style="text-align:center;"> Meeting Done </th>
                <th style="text-align:center;"> Meeting Arranged </th>
                <th style="text-align:center;"> Meeting Attempt </th>
                <th style="text-align:center;"> Meeting Pushed </th>

            </tr>
        </thead>
        <tbody>

            @foreach($users as $record)

            <?php if(isset($data[$record->id]) && !empty($data[$record->id])){ ?>
                <tr class="gradeX">
                    <td style="width:15%;">{{$record->name}}</td>
                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$followed_up )}}" target="_blank">{{$data[$record->id]['followed_up']}} </a></td>
                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$contacted_client)}}" target="_blank">{{$data[$record->id]['contacted_client']}}</a></td>
                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$call_attempt )}}" target="_blank">{{$data[$record->id]['call_attempt']}}</a></td>
                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$whatsapp_call )}}" target="_blank">{{$data[$record->id]['whatsapp_call']}} </a></td>

                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$meeting_done )}}" target="_blank">{{$data[$record->id]['meeting_done']}}</a></td>
                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$meeting_arranged )}}" target="_blank">{{$data[$record->id]['meeting_arranged']}}</a></td>
                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$meeting_attempt )}}" target="_blank">{{$data[$record->id]['meeting_attempt']}}</a></td>
                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$meeting_pushed )}}" target="_blank">{{$data[$record->id]['meeting_pushed']}}</a></td>

                </tr>
                <?php } ?>
            @endforeach
        </tbody>
    </table>


</body>
</html>
