<!DOCTYPE html>
<html>
    <head>
        <title>Calls Report</title>
    </head>
    <body>
        <style>
            table.table.ps-table th{
                background: #446161;
                color: #fff;
                font-weight: 600;
            }
            .ps-table {
                background-color: #fff;
            }
            table {
                border-collapse: separate; /*collapse;*/
                border-spacing: 1px;
            }

            .table > thead > tr > th {
                vertical-align: bottom;
                border-bottom: 2px solid #dddddd;
            }

            .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
                padding: 8px;
            }

            .ps-table tbody tr td {
                font-size: 14px;
                padding: 12px 10px;
                border: none;
                margin: 0 auto;
                vertical-align: middle;
            }
        </style>

        <h1>Calls Report</h1>
        <p>This PDF document is generated by  <b style="color: red">{{ Auth::user()->name }} </b> on  {{ \Carbon\Carbon::now('Asia/Karachi')->format('l, d-M-Y h:i A') }}.</p>

        <?php
            // $user_id = 0;
            if(app('request')->input('task') != ''){
                $select_task = app('request')->input('task');
            }else{
                $select_task = 'all';
            }

            $whatsapp_call='Whatsapp Call';
            $call_attempt='Call Attempt';

        ?>

        <div class="ps-section__content">
            <div class="table-responsive">
                <table class="table ps-table" style="table-layout: fixed; width: 100%;">
                    <thead>
                        <tr>
                            <th>User</th>
                            <th style="text-align:center;">Call Attempt</th>
                            <th style="text-align:center;"> Whatsapp Call </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach($users as $record)

                        <?php if(isset($data[$record->id]) && !empty($data[$record->id])){ ?>
                            <tr class="gradeX">
                                <td>{{$record->name}}</td>
                                <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$call_attempt )}}" target="_blank">{{$data[$record->id]['call_attempt']}}</a></td>
                                <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$whatsapp_call )}}" target="_blank">{{$data[$record->id]['whatsapp_call']}} </a></td>
                            </tr>
                            <?php } ?>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>


    </body>
</html>
