<!DOCTYPE html>
<html>
    <head>
        <title>Dealers Report</title>
    </head>
    <body>
        <style>
            table.table.ps-table th{
                background: #446161;
                color: #fff;
                font-weight: 600;
            }
            .ps-table {
                background-color: #fff;
            }
            table {
                border-collapse: separate; /*collapse;*/
                border-spacing: 1px;
            }

            .table > thead > tr > th {
                vertical-align: bottom;
                border-bottom: 2px solid #dddddd;
            }

            .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
                padding: 8px;
            }

            .ps-table tbody tr td {
                font-size: 14px;
                padding: 12px 10px;
                border: none;
                margin: 0 auto;
                vertical-align: middle;
            }
        </style>

        <h1>Dealers Report</h1>
        <p>This PDF document is generated by  <b style="color: red">{{ Auth::user()->name }} </b> on  {{ \Carbon\Carbon::now('Asia/Karachi')->format('l, d-M-Y h:i A') }}.</p>

        <?php
            if(app('request')->input('task') != ''){
                $select_task = app('request')->input('task');
            }else{
                $select_task = 'all';
            }
            $contacted_client='Contacted Client';
            $meeting_done ='Meeting (Done)';
            $report_of ='dealer';
        ?>

        <div class="ps-section__content">
            <div class="table-responsive">
                <table class="table ps-table" style="table-layout: fixed; width: 100%;">
                    <thead>
                        <tr>
                            <th>User</th>
                            <th style="text-align:center;">Contacted Client</th>
                            <th style="text-align:center;"> Meeting Done </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $record)

                            <?php if(isset($data[$record->id]) && !empty($data[$record->id])){ ?>
                                <tr class="gradeX">
                                    <td>{{$record->name}}</td>
                                    <td style="text-align:center;"><a href="{{url('report_info/'.$report_of.'/'.$record->id.'/'.$select_task.'/'.$contacted_client)}}" target="_blank">{{$data[$record->id]['dealer_contacted_client']}}</a></td>
                                    <td style="text-align:center;"><a href="{{url('report_info/'.$report_of.'/'.$record->id.'/'.$select_task.'/'.$meeting_done )}}" target="_blank">{{$data[$record->id]['dealer_meeting_done']}}</a></td>
                                </tr>
                            <?php } ?>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>
