<!DOCTYPE html>
<html>
    <head>
        <title>Sales Report</title>
    </head>
    <body>
        <style>
            table.table.ps-table th{
                background: #446161;
                color: #fff;
                font-weight: 600;
            }
            .ps-table {
                background-color: #fff;
            }
            table {
                border-collapse: separate; /*collapse;*/
                border-spacing: 1px;
            }

            .table > thead > tr > th {
                vertical-align: bottom;
                border-bottom: 2px solid #dddddd;
            }

            .table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
                padding: 8px;
            }

            .ps-table tbody tr td {
                font-size: 14px;
                padding: 12px 10px;
                border: none;
                margin: 0 auto;
                vertical-align: middle;
            }
        </style>

        <h1>Sales Report</h1>
        <p>This PDF document is generated by  <b style="color: red">{{ Auth::user()->name }} </b> on  {{ \Carbon\Carbon::now('Asia/Karachi')->format('l, d-M-Y h:i A') }}.</p>

        <?php
            if(app('request')->input('task') != ''){
                $select_task = app('request')->input('task');
            }else{
                $select_task = 'all';
            }
            $token_payment='Token Payment';
            $complete_down_payment='Complete Down Payment';
            $booking_form='Booking Form';
            $closed_won='Closed (Won)';
            $closed_lost='Closed (Lost)';
            $closed_cancelled='Closed (Cancelled)';
        ?>

        <div class="ps-section__content">
            <div class="table-responsive">
                <table class="table ps-table" style="table-layout: fixed; width: 100%;">
                    <thead>
                        <tr>
                            <th>User</th>
                            <th style="text-align:center;"> Token Payment        </th>
                            <th style="text-align:center;"> Complete Down Payment</th>
                            <th style="text-align:center;"> Booking Form         </th>
                            <th style="text-align:center;"> Closed (Won)         </th>
                            <th style="text-align:center;"> Closed (Lost)        </th>
                            <th style="text-align:center;"> Closed (Cancelled)   </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach($users as $record)

                            <?php if(isset($data[$record->id]) && !empty($data[$record->id])){ ?>
                                <tr class="gradeX">

                                    <td>{{$record->name}}</td>
                                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$token_payment )}}" target="_blank">{{$data[$record->id]['token_payment']}}</a></td>
                                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$complete_down_payment )}}" target="_blank">{{$data[$record->id]['complete_down_payment']}} </a></td>
                                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$booking_form )}}" target="_blank">{{$data[$record->id]['booking_form']}} </a></td>
                                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$closed_won )}}" target="_blank">{{$data[$record->id]['closed_won']}}</a></td>
                                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$closed_lost )}}" target="_blank">{{$data[$record->id]['closed_lost']}} </a></td>
                                    <td style="text-align:center;"><a href="{{url('report_info/'.$record->id.'/'.$select_task.'/'.$closed_cancelled )}}" target="_blank">{{$data[$record->id]['closed_cancelled']}} </a></td>

                                </tr>
                            <?php } ?>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>
